name: usage
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  encrypt: ^1.0.1
  rxdart: ^0.21.0
  http: ^0.12.0+1
  url_launcher: ^5.0.2
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.1+4
  flutter_local_notifications: ^0.5.2
  local_auth: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
